cache:
  paths:
  - node_modules/

stages:
  - build
  - deploy
  - verify

build:
  stage: build
  script:
  - docker-compose build

deploy:
  stage: deploy
  script:
  - docker-compose down --remove-orphans
  - docker-compose up -d

check-container:
  stage: verify
  script:
  - echo "Checking that container for ${CI_PROJECT_NAME//-} is running..."
  - test "$(docker ps | grep ${CI_PROJECT_NAME//-})"

get-logs:
  stage: verify
  script:
  - docker logs -t "$(docker ps -a | grep ${CI_PROJECT_NAME//-} | awk '{print $1;}')"